### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by Deepp0925** [j0j00/flutter_liquidcore#14]
@j0j00, I am getting "<LiquidCore/LiquidCore.h> file not found" error while running the example project

pods were successfully installed

**Comment by j0j00** [comment]
I unfortunately don't have much free to time to work on the project at the moment.

If you're able to fix the issue, then feel free to put in a PR and I'll be sure to merge and publish it pending testing.

**Comment by Deepp0925** [comment]
@j0j00 It started working after I ran 
1. `sudo gem install cocoapods`
2. clean build folder
3. run with legacy build

although this raised a new error 'flutter_assets no such file or directory in /path/2/project/ios/Flutter' in Xcode 11.4.1 but I was able to suppress this issue by copying the flutter_assets from App.framework folder to Flutter folder
