### ISSUE TITLE
Using JSContext not able to execute functions in Javascript

### ISSUE THREAD

**Issue by braj065** [j0j00/flutter_liquidcore#18]
If i am trying to execute a JS function as follows - function show_number(){return 10+7;}() I am getting error that 'SyntaxError: Unexpected token )'

_jsContext.evaluateScript('function show_random_number(){return 10+7;}()');

**Comment by j0j00** [comment]
The GitHub issues are for bugs in the library. This is an issue with your code.

It's not valid JavaScript, hence the syntax error.

Questions like this are more for stackoverflow.
